
-- 6) Daily max amount & transaction count per terminal
SELECT TRANDATE, TERMINALNO, MAX(AMOUNT) AS MAX_AMOUNT, COUNT(AMOUNT) AS TRANSACTION_COUNT
FROM tb_transactions
GROUP BY TRANDATE, TERMINALNO
ORDER BY MAX(AMOUNT)