
-- 5) Total amount & transaction count per terminal in Bahman
SELECT  TERMINALNO, SUM(AMOUNT) AS TOTAL_AMOUNT, COUNT(AMOUNT) AS TRANSACTION_COUNT
FROM tb_transactions
WHERE TRANDATE BETWEEN '1401-11-01' AND '1401-11-30' --Bahman
GROUP BY TERMINALNO
ORDER BY SUM(AMOUNT) DESC 